apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-deployment
  namespace: banking   # Added namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
      - name: banking
        image: pradeeproy66/banking:latest  # Updated Docker image
        ports:
        - containerPort: 8082   # Updated port to match your app
