apiVersion: v1
kind: Service
metadata:
  name: banking-service
  namespace: banking
spec:
  selector:
    app: banking
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
